# Site settings
title: "Resume"
description: "A resume of Yuan Ning."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Yuan Ning"
resume_title:                   "Undergraduated student"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "yuanning.nn@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+86 139 4912 2613"
resume_contact_address:         "10 Cuizhu Street, Gaoxin District, Zhengzhou, Henan, 450000, China "

resume_header_contact_info:     "10 Cuizhu Street, Gaoxin District, Zhengzhou, Henan, 450000, China • +86 139 4912 2613 • yuanning.nn@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p style='font-style: italic; text-align: center; font-size: 1.5em;'>\"Ob nicht Natur zuletzt sich doch ergründe?\"</p><p style='text-align: center; font-size: 1.2em;'>— Johann Wolfgang von Goethe</p>"


# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    false
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/YuanN1ng"
 # resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
 # resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://yuann1ng.github.io"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
